### ISSUE TITLE
Add "Import keys from github" option

### ISSUE THREAD

**Issue by lrvick** [hashbang/hashbangctl#2]
One can easily import public keys from a github username via their JSON api like so:

https://api.github.com/users/lrvick/keys

Providing a "import keys from github" could greatly simplify the process of enabling multi-key users to be able to log in from all their usual systems.

**Comment by ghost** [comment]
I'll work on this too, if I have the time. Shouldn't be too hard for this either.

**Comment by daveloyall** [comment]
That's a great idea, I just manually did this earlier today.  Consider putting some UI around it so it doesn't just import _all_ of them.  I have some keys in my github that aren't needed here.

Keep up the good work!

**Comment by ghost** [comment]
>  AlissaSquared commented on May 3 

To clarify, no, I haven't had time x-x I'll look into it if someone pokes me enough though

**Comment by KellerFuchs** [comment]
It has been implemented in #10.
